### ISSUE TITLE
Composer.json tweaks

### ISSUE THREAD

**Issue by robinkanters** [robinkanters/php-promises#23]
- [ ] [Authors](https://getcomposer.org/doc/04-schema.md#authors)
- [ ] [Homepage](https://getcomposer.org/doc/04-schema.md#homepage)
- [ ] [Keywords](https://getcomposer.org/doc/04-schema.md#keywords)
